import type { Objective, KeyResult, Action, ActionLog, WeeklyRetro, RetroSnapshot } from '../../shared/db';
import { calcObjectiveProgress } from '../okr/progress';
import { detectStagnantKeyResults } from '../stagnation/detector';

interface RetroInput {
  objectives: Objective[];
  keyResults: KeyResult[];
  actions: Action[];
  actionLogs: ActionLog[];
  weekStart: Date;
}

/**
 * Auto-generate a WeeklyRetro from the current state.
 */
export function generateWeeklyRetro(input: RetroInput): Omit<WeeklyRetro, 'id'> {
  const { objectives, keyResults, actions, actionLogs, weekStart } = input;

  const weekEnd = new Date(weekStart);
  weekEnd.setDate(weekEnd.getDate() + 7);

  const weekLogs = actionLogs.filter((log) => {
    const d = new Date(log.loggedAt);
    return d >= weekStart && d < weekEnd;
  });

  const completedActions = actions.filter((a) => a.status === 'done').length;
  const totalActions = actions.length;
  const avgMood = weekLogs.length > 0
    ? weekLogs.reduce((sum, l) => sum + l.mood, 0) / weekLogs.length
    : 0;

  const snapshot: RetroSnapshot = {
    objectives,
    keyResults,
    completedActions,
    totalActions,
    avgMood,
  };

  // Auto-generate wins from completed actions this week
  const wins: string[] = weekLogs
    .filter((l) => l.note)
    .slice(0, 3)
    .map((l) => l.note);

  // Auto-generate blockers from stagnant KRs
  const stagnant = detectStagnantKeyResults(keyResults);
  const blockers: string[] = stagnant
    .slice(0, 3)
    .map((kr) => `「${kr.title}」が停滞しています`);

  // Auto-generate focus suggestions based on lowest-progress KRs
  const sorted = [...keyResults]
    .filter((kr) => kr.status !== 'completed')
    .sort((a, b) => {
      const pa = a.targetValue > 0 ? a.currentValue / a.targetValue : 0;
      const pb = b.targetValue > 0 ? b.currentValue / b.targetValue : 0;
      return pa - pb;
    });

  const focusNext: string[] = sorted.slice(0, 3).map((kr) => {
    const obj = objectives.find((o) => {
      const progress = calcObjectiveProgress(o, keyResults);
      return progress >= 0; // just find related
    });
    void obj;
    return `「${kr.title}」の進捗を上げる`;
  });

  const progressLines = objectives
    .filter((o) => o.status === 'active')
    .map((o) => {
      const pct = calcObjectiveProgress(o, keyResults).toFixed(0);
      return `- ${o.title}: ${pct}%`;
    })
    .join('\n');

  const autoGeneratedSummary = `
今週の振り返りを自動生成しました。

## 進捗サマリー
${progressLines || '目標が設定されていません'}

## 完了アクション
${completedActions} / ${totalActions} 件

## 平均気分スコア
${avgMood > 0 ? avgMood.toFixed(1) + ' / 5' : 'データなし'}
`.trim();

  return {
    weekStart,
    snapshot,
    autoGeneratedSummary,
    wins: wins.length > 0 ? wins : ['今週のログを記録してください'],
    blockers: blockers.length > 0 ? blockers : [],
    focusNext: focusNext.length > 0 ? focusNext : [],
    createdAt: new Date(),
  };
}
