import { useState } from 'react';
import { motion } from 'framer-motion';
import { useOkrStore } from '../../shared/store';
import { generateWeeklyRetro } from '../../core/retro';
import { db } from '../../shared/db';
import { Card, Button } from '../../shared/components';
import type { WeeklyRetro } from '../../shared/db';

function getWeekStart(date: Date): Date {
  const d = new Date(date);
  const day = d.getDay();
  const diff = d.getDate() - day + (day === 0 ? -6 : 1);
  d.setDate(diff);
  d.setHours(0, 0, 0, 0);
  return d;
}

export function RetroPage() {
  const { objectives, keyResults, actions, actionLogs } = useOkrStore();
  const [retro, setRetro] = useState<Omit<WeeklyRetro, 'id'> | null>(null);
  const [saved, setSaved] = useState(false);
  const [loading, setLoading] = useState(false);

  function handleGenerate() {
    const weekStart = getWeekStart(new Date());
    const result = generateWeeklyRetro({
      objectives,
      keyResults,
      actions,
      actionLogs,
      weekStart,
    });
    setRetro(result);
    setSaved(false);
  }

  async function handleSave() {
    if (!retro) return;
    setLoading(true);
    await db.weeklyRetros.add(retro);
    setSaved(true);
    setLoading(false);
  }

  return (
    <div className="max-w-2xl mx-auto px-4 py-6 space-y-6">
      <div className="flex items-center justify-between">
        <h1 className="text-2xl font-bold text-gray-900">週次レトロスペクティブ</h1>
        <Button onClick={handleGenerate} size="sm">
          自動生成
        </Button>
      </div>

      {!retro ? (
        <Card className="text-center py-12">
          <p className="text-gray-500 mb-4">今週の振り返りを自動生成します</p>
          <Button onClick={handleGenerate}>レトロを生成する</Button>
        </Card>
      ) : (
        <motion.div
          initial={{ opacity: 0, y: 16 }}
          animate={{ opacity: 1, y: 0 }}
          className="space-y-4"
        >
          {/* Summary */}
          <Card>
            <h2 className="font-semibold text-gray-800 mb-2">自動生成サマリー</h2>
            <pre className="text-sm text-gray-700 whitespace-pre-wrap font-sans">
              {retro.autoGeneratedSummary}
            </pre>
          </Card>

          {/* Wins */}
          <Card>
            <h2 className="font-semibold text-green-700 mb-2">今週の成果</h2>
            <ul className="space-y-1">
              {retro.wins.map((win, i) => (
                <li key={i} className="text-sm text-gray-700 flex items-start gap-2">
                  <span className="text-green-500 mt-0.5" aria-hidden="true">+</span>
                  {win}
                </li>
              ))}
            </ul>
          </Card>

          {/* Blockers */}
          {retro.blockers.length > 0 && (
            <Card className="border-orange-200">
              <h2 className="font-semibold text-orange-700 mb-2">ブロッカー</h2>
              <ul className="space-y-1">
                {retro.blockers.map((blocker, i) => (
                  <li key={i} className="text-sm text-orange-700 flex items-start gap-2">
                    <span aria-hidden="true">!</span>
                    {blocker}
                  </li>
                ))}
              </ul>
            </Card>
          )}

          {/* Next Focus */}
          <Card>
            <h2 className="font-semibold text-blue-700 mb-2">来週のフォーカス</h2>
            <ul className="space-y-1">
              {retro.focusNext.map((focus, i) => (
                <li key={i} className="text-sm text-gray-700 flex items-start gap-2">
                  <span className="text-blue-500 mt-0.5 font-bold" aria-hidden="true">{i + 1}.</span>
                  {focus}
                </li>
              ))}
            </ul>
          </Card>

          <div className="flex justify-end gap-2">
            <Button variant="ghost" size="sm" onClick={handleGenerate}>
              再生成
            </Button>
            <Button
              size="sm"
              onClick={handleSave}
              loading={loading}
              disabled={saved}
            >
              {saved ? '保存済み' : '保存する'}
            </Button>
          </div>
        </motion.div>
      )}
    </div>
  );
}
