import Dexie, { type Table } from 'dexie';

// ─── Data Model Types ───────────────────────────────────────────────────────

export type ObjectiveStatus = 'active' | 'completed' | 'archived';
export type KeyResultStatus = 'on_track' | 'at_risk' | 'behind' | 'completed';
export type ActionStatus = 'todo' | 'in_progress' | 'done' | 'skipped';
export type ActionPriority = 'high' | 'medium' | 'low';
export type MoodScore = 1 | 2 | 3 | 4 | 5;
export type AIProvider = 'openai' | 'anthropic' | 'local';
export type FocusSource = 'auto' | 'manual';

export interface Objective {
  id?: number;
  title: string;
  quarter: string; // e.g. "2026Q2"
  status: ObjectiveStatus;
  createdAt: Date;
  updatedAt: Date;
}

export interface KeyResult {
  id?: number;
  objectiveId: number;
  title: string;
  targetValue: number;
  currentValue: number;
  unit: string;
  dueDate: Date;
  lastActivityAt: Date;
  status: KeyResultStatus;
}

export interface Action {
  id?: number;
  keyResultId: number;
  title: string;
  estimatedMinutes: number;
  priority: ActionPriority;
  tags: string[];
  status: ActionStatus;
}

export interface ActionLog {
  id?: number;
  actionId: number;
  loggedAt: Date;
  note: string;
  progressDelta: number;
  mood: MoodScore;
}

export interface WeeklyRetro {
  id?: number;
  weekStart: Date;
  snapshot: RetroSnapshot;
  autoGeneratedSummary: string;
  wins: string[];
  blockers: string[];
  focusNext: string[];
  createdAt: Date;
}

export interface RetroSnapshot {
  objectives: Objective[];
  keyResults: KeyResult[];
  completedActions: number;
  totalActions: number;
  avgMood: number;
}

export interface DailyFocus {
  id?: number;
  date: Date;
  actionIds: number[];
  source: FocusSource;
}

export interface AppSettings {
  id?: number;
  aiApiKey: string;
  aiProvider: AIProvider;
  syncEnabled: boolean;
  ritualSettings: RitualSettings;
}

export interface RitualSettings {
  enabled: boolean;
  soundEnabled: boolean;
  confettiEnabled: boolean;
  streakGoal: number;
}

// ─── Dexie Database ─────────────────────────────────────────────────────────

export class OkrTrackerDB extends Dexie {
  objectives!: Table<Objective, number>;
  keyResults!: Table<KeyResult, number>;
  actions!: Table<Action, number>;
  actionLogs!: Table<ActionLog, number>;
  weeklyRetros!: Table<WeeklyRetro, number>;
  dailyFocus!: Table<DailyFocus, number>;
  appSettings!: Table<AppSettings, number>;

  constructor() {
    super('okr-tracker-db');

    this.version(1).stores({
      objectives: '++id, quarter, status, createdAt, updatedAt',
      keyResults: '++id, objectiveId, dueDate, lastActivityAt, status',
      actions: '++id, keyResultId, priority, status, *tags',
      actionLogs: '++id, actionId, loggedAt, mood',
      weeklyRetros: '++id, weekStart, createdAt',
      dailyFocus: '++id, date',
      appSettings: '++id',
    });
  }
}

export const db = new OkrTrackerDB();
